# Generated by Django 6.0.8 on 2026-08-05 11:46

import django.db.models.deletion
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], db_index=True, max_length=5)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1500)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('bags', 'Bags'), ('clothing', 'Clothing'), ('documents', 'Documents'), ('keys', 'Keys'), ('wallets', 'Wallets'), ('jewellery', 'Jewellery'), ('books', 'Books'), ('other', 'Other')], db_index=True, max_length=20)),
                ('colour', models.CharField(db_index=True, max_length=50)),
                ('campus_location', models.CharField(choices=[('main_entrance', 'Main Entrance'), ('library', 'Library'), ('cafeteria', 'Cafeteria'), ('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('student_affairs', 'Student Affairs'), ('sports_area', 'Sports Area'), ('other', 'Other')], db_index=True, max_length=30)),
                ('item_date', models.DateField(db_index=True, verbose_name='date lost or found')),
                ('image', models.ImageField(upload_to=items.models.report_image_path, validators=[items.models.validate_image_size])),
                ('status', models.CharField(choices=[('active', 'Active'), ('possible_match', 'Possible Match'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'status', '-created_at'], name='items_itemr_report__5477bf_idx')],
            },
        ),
    ]
