# Generated by Django 6.0.8 on 2026-08-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreport',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden reports are visible only to their owner and staff members.'),
        ),
    ]
