# Generated by Django 6.0.8 on 2026-08-05 17:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemreport_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('ownership_claim', 'Ownership Claim'), ('found_item', 'Found Item')], max_length=24)),
                ('initial_message', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('private_details', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('item_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='items.itemreport')),
                ('receiving_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_contact_requests', to=settings.AUTH_USER_MODEL)),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_contact_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contact_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_contact_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='items.contactrequest')),
                ('first_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_first', to=settings.AUTH_USER_MODEL)),
                ('item_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='items.itemreport')),
                ('second_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_second', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('request_created', 'Contact request created'), ('request_cancelled', 'Contact request cancelled'), ('request_approved', 'Request approved'), ('request_denied', 'Request denied'), ('permission_revoked', 'Permission revoked'), ('conversation_opened', 'Conversation opened'), ('message_sent', 'Message sent'), ('message_read', 'Message read'), ('phone_granted', 'Phone-number access granted'), ('phone_blocked', 'Phone-number access blocked')], db_index=True, max_length=24)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.CharField(max_length=255)),
                ('acting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_audit_events', to=settings.AUTH_USER_MODEL)),
                ('item_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_audit_events', to='items.itemreport')),
                ('contact_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='items.contactrequest')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='items.conversation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='items.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[items.models.validate_phone_number])),
                ('consent_to_share_phone', models.BooleanField(default=False, help_text='When enabled, your phone number is shown only after staff approve a contact request. You can revoke consent at any time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='contactrequest',
            constraint=models.CheckConstraint(condition=models.Q(('requesting_user', models.F('receiving_user')), _negated=True), name='contact_request_different_users'),
        ),
        migrations.AddConstraint(
            model_name='contactrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('item_report', 'requesting_user', 'receiving_user'), name='unique_pending_contact_request'),
        ),
    ]
