# Generated by Django 6.0.8 on 2026-08-06 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_conversation_closed_at_conversation_closed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('enabled_by_default', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AIAssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('provider_name', models.CharField(default='Local deterministic provider', max_length=80)),
                ('model_name', models.CharField(default='findmatch-local-v1', max_length=80)),
                ('request_timeout_seconds', models.PositiveSmallIntegerField(default=15)),
                ('maximum_input_length', models.PositiveIntegerField(default=5000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_assistant_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI assistant settings',
                'permissions': (('manage_ai_assistant', 'Can manage global AI assistant settings'),),
            },
        ),
        migrations.CreateModel(
            name='AICapabilityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('assistant_enabled', 'Assistant Enabled'), ('assistant_disabled', 'Assistant Disabled'), ('capability_enabled', 'Capability Enabled'), ('capability_disabled', 'Capability Disabled'), ('override_changed', 'Override Changed'), ('request_executed', 'Request Executed'), ('request_blocked', 'Request Blocked'), ('provider_failure', 'Provider Failure')], db_index=True, max_length=24)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(default='global', max_length=40)),
                ('safe_description', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acting_administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_capability_audit_events', to=settings.AUTH_USER_MODEL)),
                ('capability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='items.aicapability')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AICapabilitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_setting', to='items.aicapability')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_capability_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminCapabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(choices=[('inherit', 'Inherit Global Setting'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='inherit', max_length=10)),
                ('administrator', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_capability_overrides', to=settings.AUTH_USER_MODEL)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_overrides', to='items.aicapability')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('administrator', 'capability'), name='unique_ai_capability_override')],
            },
        ),
    ]
