# Generated by Django 6.0.8 on 2026-08-10 12:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_conversation_states(apps, schema_editor):
    Conversation = apps.get_model("items", "Conversation")
    Conversation.objects.filter(status__in=("pending", "reopened")).update(
        status="active", is_active=True
    )


def reverse_normalize_conversation_states(apps, schema_editor):
    # Active is a valid state in both schemas; the former distinction cannot be
    # reconstructed reliably and is intentionally left as active on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_message_privacy_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='items_messa_convers_f4b80c_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hide_approved_confirmed_messages',
        ),
        migrations.AddField(
            model_name='conversation',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deactivation_reason',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='contactauditlog',
            name='event_type',
            field=models.CharField(choices=[('request_created', 'Contact request created'), ('request_cancelled', 'Contact request cancelled'), ('request_approved', 'Request approved'), ('request_denied', 'Request denied'), ('permission_revoked', 'Permission revoked'), ('conversation_opened', 'Conversation opened'), ('message_sent', 'Message sent'), ('message_read', 'Message read'), ('phone_granted', 'Phone-number access granted'), ('phone_blocked', 'Phone-number access blocked'), ('phone_masked', 'Masked phone number displayed'), ('bulk_report_action', 'Bulk report action'), ('deal_completed', 'Deal completed'), ('conversation_reopened', 'Conversation reopened'), ('conversation_deactivated', 'Conversation deactivated')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('initiated', 'Conversation Started'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=12),
        ),
        migrations.RunPython(
            normalize_conversation_states,
            reverse_normalize_conversation_states,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('deal_completed', 'Deal Completed'), ('conversation_reopened', 'Conversation Reopened'), ('conversation_deactivated', 'Conversation Deactivated'), ('contact_approved', 'Contact Request Approved'), ('contact_denied', 'Contact Request Denied'), ('report_status_changed', 'Report Status Changed'), ('admin_notice', 'Administrator Notice')], db_index=True, max_length=28),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('item_report', 'first_participant', 'second_participant'), name='unique_report_participant_conversation'),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='message',
            name='hidden_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='hidden_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_important_context',
        ),
        migrations.RemoveField(
            model_name='message',
            name='retention_expires_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='visibility',
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked_user'), name='unique_user_block'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked_user')), _negated=True), name='user_cannot_block_self'),
        ),
    ]
