# Generated by Django 6.0.8 on 2026-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_simplify_conversations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_unmasked_phone_numbers', 'Can view unmasked shared phone numbers'),)},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mask_phone_number',
            field=models.BooleanField(default=True, help_text='Show active conversation contacts only the final four digits of your phone number.'),
        ),
    ]
