# Generated by Django 6.0.8 on 2026-08-12 10:56

import django.core.validators
import django.db.models.deletion
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_update_phone_permission_wording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=items.models.claim_evidence_path, validators=[items.models.validate_evidence_size, django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'pdf'))])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandoverConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateVerificationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('hidden_mark', 'Describe a hidden mark.'), ('contents', 'What was inside the item?'), ('exact_location', 'Where exactly was it lost?'), ('lock_screen', 'What does the lock screen look like?'), ('accessory', 'Describe a unique accessory.'), ('serial_part', 'Provide part of the serial number.'), ('engraving', 'Describe an engraving.'), ('other', 'Other private verification question')], max_length=30)),
                ('question_text', models.CharField(blank=True, max_length=240)),
                ('expected_answer', models.TextField(max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SuspiciousClaimReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='contactrequest',
            name='unique_pending_contact_request',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='clarification_answer',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='clarification_request',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='loss_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='loss_timeframe',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='truthful_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='additional_details',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='approximate_size',
            field=models.CharField(blank=True, choices=[('xs', 'Extra Small'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'Extra Large'), ('not_sure', 'Not Sure')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='brand',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi'), ('lenovo', 'Lenovo'), ('hp', 'HP'), ('dell', 'Dell'), ('asus', 'ASUS'), ('sony', 'Sony'), ('adidas', 'Adidas'), ('nike', 'Nike'), ('puma', 'Puma'), ('no_visible_brand', 'No Visible Brand'), ('other', 'Other'), ('not_sure', 'Not Sure')], db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='custom_brand',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='custom_item_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='custom_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='item_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('used', 'Used'), ('damaged', 'Damaged'), ('not_sure', 'Not Sure')], max_length=20),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='item_type',
            field=models.CharField(blank=True, choices=[('mobile_phone', 'Mobile Phone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('smartwatch', 'Smartwatch'), ('earbuds', 'Earbuds'), ('headphones', 'Headphones'), ('charger', 'Charger'), ('cable', 'Cable'), ('power_bank', 'Power Bank'), ('camera', 'Camera'), ('calculator', 'Calculator'), ('usb_drive', 'USB Drive'), ('other', 'Other'), ('not_sure', 'Not Sure'), ('backpack', 'Backpack'), ('handbag', 'Handbag'), ('laptop_bag', 'Laptop Bag'), ('school_bag', 'School Bag'), ('sports_bag', 'Sports Bag'), ('suitcase', 'Suitcase'), ('shopping_bag', 'Shopping Bag'), ('jacket', 'Jacket'), ('coat', 'Coat'), ('shirt', 'Shirt'), ('t_shirt', 'T-Shirt'), ('trousers', 'Trousers'), ('dress', 'Dress'), ('shoes', 'Shoes'), ('hat', 'Hat'), ('scarf', 'Scarf'), ('gloves', 'Gloves'), ('student_id', 'Student ID Card'), ('bank_card', 'Bank Card'), ('transport_card', 'Transportation Card'), ('driver_licence', "Driver's Licence"), ('national_id', 'National ID Card'), ('passport', 'Passport'), ('certificate', 'Certificate'), ('notebook', 'Notebook'), ('house_keys', 'House Keys'), ('car_keys', 'Car Keys'), ('office_keys', 'Office Keys'), ('locker_key', 'Locker Key'), ('keychain', 'Keychain'), ('electronic_key', 'Electronic Key'), ('wallet', 'Wallet'), ('purse', 'Purse'), ('card_holder', 'Card Holder'), ('coin_purse', 'Coin Purse'), ('ring', 'Ring'), ('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('earrings', 'Earrings'), ('watch', 'Watch'), ('textbook', 'Textbook'), ('folder', 'Folder'), ('pencil_case', 'Pencil Case'), ('pen', 'Pen'), ('ball', 'Ball'), ('racket', 'Racket'), ('sports_clothing', 'Sports Clothing'), ('water_bottle', 'Water Bottle'), ('glasses', 'Glasses'), ('sunglasses', 'Sunglasses'), ('umbrella', 'Umbrella'), ('head_covering', 'Head Covering')], db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='material',
            field=models.CharField(blank=True, choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('leather', 'Leather'), ('fabric', 'Fabric'), ('glass', 'Glass'), ('paper', 'Paper'), ('wood', 'Wood'), ('rubber', 'Rubber'), ('mixed', 'Mixed Materials'), ('other', 'Other'), ('not_sure', 'Not Sure')], db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='pattern',
            field=models.CharField(blank=True, choices=[('plain', 'Plain'), ('striped', 'Striped'), ('checked', 'Checked'), ('printed', 'Printed'), ('floral', 'Floral'), ('logo', 'Logo'), ('multicoloured', 'Multicoloured'), ('other', 'Other'), ('not_sure', 'Not Sure')], max_length=30),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='primary_colour',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('grey', 'Grey'), ('silver', 'Silver'), ('red', 'Red'), ('blue', 'Blue'), ('dark_blue', 'Dark Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('beige', 'Beige'), ('gold', 'Gold'), ('multicoloured', 'Multicoloured'), ('transparent', 'Transparent'), ('other', 'Other'), ('not_sure', 'Not Sure')], db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='require_official_handover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='secondary_colour',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('grey', 'Grey'), ('silver', 'Silver'), ('red', 'Red'), ('blue', 'Blue'), ('dark_blue', 'Dark Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('beige', 'Beige'), ('gold', 'Gold'), ('multicoloured', 'Multicoloured'), ('transparent', 'Transparent'), ('other', 'Other'), ('not_sure', 'Not Sure')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contactauditlog',
            name='event_type',
            field=models.CharField(choices=[('request_created', 'Contact request created'), ('request_cancelled', 'Contact request cancelled'), ('request_approved', 'Request approved'), ('request_denied', 'Request denied'), ('request_more_info', 'More information requested'), ('additional_answer', 'Additional answer submitted'), ('claim_disputed', 'Claim disputed'), ('suspicious_claim', 'Suspicious claim reported'), ('permission_revoked', 'Permission revoked'), ('conversation_opened', 'Conversation opened'), ('message_sent', 'Message sent'), ('message_read', 'Message read'), ('phone_granted', 'Phone-number access granted'), ('phone_blocked', 'Phone-number access blocked'), ('phone_masked', 'Masked phone number displayed'), ('bulk_report_action', 'Bulk report action'), ('deal_completed', 'Deal completed'), ('conversation_reopened', 'Conversation reopened'), ('conversation_deactivated', 'Conversation deactivated')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('initiated', 'Conversation Started'), ('pending', 'Pending'), ('more_information', 'More Information Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=24),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='campus_location',
            field=models.CharField(choices=[('main_entrance', 'Main Entrance'), ('library', 'Library'), ('cafeteria', 'Cafeteria'), ('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('student_affairs', 'Student Affairs'), ('sports_area', 'Sports Area'), ('administration', 'Administration Building'), ('conference_hall', 'Conference Hall'), ('university_garden', 'University Garden'), ('parking', 'Parking Area'), ('bus_stop', 'Shuttle or Bus Stop'), ('restroom', 'Restroom'), ('prayer_area', 'Prayer Area'), ('other', 'Other'), ('not_sure', 'Not Sure')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('bags', 'Bags'), ('clothing', 'Clothing'), ('documents', 'Documents'), ('keys', 'Keys'), ('wallets', 'Wallets and Purses'), ('jewellery', 'Jewellery'), ('books', 'Books and Stationery'), ('sports_equipment', 'Sports Equipment'), ('personal_accessories', 'Personal Accessories'), ('other', 'Other'), ('not_sure', 'Not Sure')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='contactrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'more_information'))), fields=('item_report', 'requesting_user', 'receiving_user'), name='unique_pending_contact_request'),
        ),
        migrations.AddField(
            model_name='claimanswer',
            name='contact_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='items.contactrequest'),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='contact_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='items.contactrequest'),
        ),
        migrations.AddField(
            model_name='handoverconfirmation',
            name='contact_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_confirmations', to='items.contactrequest'),
        ),
        migrations.AddField(
            model_name='handoverconfirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privateverificationquestion',
            name='item_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_questions', to='items.itemreport'),
        ),
        migrations.AddField(
            model_name='claimanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_answers', to='items.privateverificationquestion'),
        ),
        migrations.AddField(
            model_name='suspiciousclaimreport',
            name='contact_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspicion_report', to='items.contactrequest'),
        ),
        migrations.AddField(
            model_name='suspiciousclaimreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_suspicious_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='handoverconfirmation',
            constraint=models.UniqueConstraint(fields=('contact_request', 'user'), name='unique_handover_confirmation'),
        ),
        migrations.AddConstraint(
            model_name='privateverificationquestion',
            constraint=models.UniqueConstraint(fields=('item_report', 'position'), name='unique_verification_position'),
        ),
        migrations.AddConstraint(
            model_name='claimanswer',
            constraint=models.UniqueConstraint(fields=('contact_request', 'question'), name='unique_claim_question_answer'),
        ),
    ]
