# Generated by Django 6.0.8 on 2026-08-12 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_claimanswer_claimevidence_handoverconfirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='private_details',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
