# Generated by Django 6.0.8 on 2026-08-12 11:16

import django.core.validators
import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_contactrequest_private_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimevidence',
            name='file',
            field=models.FileField(upload_to=items.models.claim_evidence_path, validators=[items.models.validate_evidence_size, items.models.validate_evidence_content, django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'pdf'))]),
        ),
    ]
