# Generated by Django 6.0.8 on 2026-08-12 11:26

import django.core.files.storage
import django.core.validators
import items.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_claimevidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimevidence',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/pc/Documents/ChatGPT/internship/private_media')), upload_to=items.models.claim_evidence_path, validators=[items.models.validate_evidence_size, items.models.validate_evidence_content, django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'pdf'))]),
        ),
    ]
