# Generated by Django 6.0.8 on 2026-08-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_claimevidence_file'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='admincapabilityoverride',
            name='unique_ai_capability_override',
        ),
        migrations.RemoveField(
            model_name='aicapabilityauditlog',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='aicapabilitysetting',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='aicapabilityauditlog',
            name='acting_administrator',
        ),
        migrations.RemoveField(
            model_name='aicapabilitysetting',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='admincapabilityoverride',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='admincapabilityoverride',
            name='capability',
        ),
        migrations.DeleteModel(
            name='AIAssistantSettings',
        ),
        migrations.DeleteModel(
            name='AICapabilityAuditLog',
        ),
        migrations.DeleteModel(
            name='AICapabilitySetting',
        ),
        migrations.DeleteModel(
            name='AdminCapabilityOverride',
        ),
        migrations.DeleteModel(
            name='AICapability',
        ),
    ]
