# Generated by Django 6.0.8 on 2026-08-14 09:56

import django.core.validators
import django.db.models.deletion
import items.models
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def preserve_legacy_workflows(apps, schema_editor):
    ItemReport = apps.get_model("items", "ItemReport")
    UserProfile = apps.get_model("items", "UserProfile")
    now = timezone.now()
    # The former possible_match state represented an active report. Keep those
    # records public/matchable under the new strict Active-only rule.
    ItemReport.objects.filter(status="possible_match").update(status="active")
    ItemReport.objects.filter(status="active", expires_at__isnull=True).update(
        expires_at=now + timedelta(days=90)
    )
    # Existing accounts predate email verification. Preserve their established
    # claim/message access; all newly registered accounts must verify normally.
    UserProfile.objects.filter(email_verified_at__isnull=True, user__email__gt="").update(
        email_verified_at=now
    )


def reverse_legacy_workflows(apps, schema_editor):
    # Status/verification provenance cannot be reconstructed safely.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_remove_stale_ai_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('item_report', 'Item report'), ('message', 'Message'), ('user', 'User'), ('return', 'Return or delivery')], db_index=True, max_length=16)),
                ('target_identifier', models.PositiveBigIntegerField()),
                ('reason', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('accepted', 'Accepted into custody'), ('released', 'Released for collection'), ('collected', 'Collected')], max_length=24)),
                ('handover_reference', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Organization staff'), ('manager', 'Organization manager')], default='staff', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_method', models.CharField(blank=True, choices=[('safe_public_meeting', 'Meet at a safe public location'), ('trusted_organization', 'Trusted organization or official return point'), ('security', 'University, company, or building security'), ('police_lost_property', 'Police or official lost-property office'), ('local_pickup', 'Local pickup'), ('courier_post', 'Courier or postal delivery'), ('custom', 'Custom arrangement through the private conversation')], max_length=32)),
                ('status', models.CharField(choices=[('arranging', 'Arranging Return'), ('ready_pickup', 'Ready for Pickup'), ('sent', 'Sent'), ('handed_over', 'Handed Over'), ('awaiting_receipt', 'Awaiting Receipt Confirmation'), ('received', 'Received'), ('failed_delivery', 'Failed Delivery'), ('disputed', 'Disputed')], db_index=True, default='arranging', max_length=24)),
                ('safe_public_location', models.CharField(blank=True, max_length=240)),
                ('custom_arrangement', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('delivery_address', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('address_consent_at', models.DateTimeField(blank=True, null=True)),
                ('address_consent_withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_cost_payer', models.CharField(blank=True, choices=[('finder', 'Finder'), ('owner', 'Owner'), ('shared', 'Shared'), ('none', 'No delivery cost')], max_length=16)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('tracking_reference', models.CharField(blank=True, max_length=160)),
                ('handover_reference', models.CharField(blank=True, max_length=80)),
                ('failure_report', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('finder_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_details_retention_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('legal_or_safety_hold', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('manage_return_disputes', 'Can manage return disputes'),),
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SavedSearchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('organization_type', models.CharField(choices=[('university', 'University or school'), ('police_security', 'Police or security office'), ('airport', 'Airport'), ('shopping_centre', 'Shopping centre'), ('hotel', 'Hotel'), ('public_transport', 'Public transport lost-property office'), ('company_security', 'Company security department'), ('other', 'Other official lost-property organization')], db_index=True, max_length=32)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('public_location', models.CharField(max_length=240)),
                ('public_contact', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='itemreport',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='duplicate_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='exact_private_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='image_sha256',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='place_name',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='place_type',
            field=models.CharField(blank=True, choices=[('university_school', 'University or school'), ('airport', 'Airport'), ('public_transport', 'Public transport'), ('shopping_centre', 'Shopping centre'), ('shop', 'Shop'), ('restaurant_cafe', 'Restaurant or cafe'), ('hotel', 'Hotel'), ('office_workplace', 'Office or workplace'), ('hospital_clinic', 'Hospital or clinic'), ('police_security', 'Police or security office'), ('street_public', 'Street or public area'), ('park_recreation', 'Park or recreation area'), ('sports_facility', 'Sports facility'), ('residential', 'Residential area'), ('event_venue', 'Event venue'), ('other', 'Other'), ('not_sure', 'Not Sure')], db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='public_latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='public_location',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='public_location_precision_km',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='public_longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deactivation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deactivation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_claim_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_strong_matches',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('ar', 'العربية')], default='en', max_length=8),
        ),
        migrations.AlterField(
            model_name='contactauditlog',
            name='event_type',
            field=models.CharField(choices=[('request_created', 'Contact request created'), ('request_cancelled', 'Contact request cancelled'), ('request_approved', 'Request approved'), ('request_denied', 'Request denied'), ('request_more_info', 'More information requested'), ('additional_answer', 'Additional answer submitted'), ('claim_disputed', 'Claim disputed'), ('suspicious_claim', 'Suspicious claim reported'), ('permission_revoked', 'Permission revoked'), ('conversation_opened', 'Conversation opened'), ('message_sent', 'Message sent'), ('message_read', 'Message read'), ('phone_granted', 'Phone-number access granted'), ('phone_blocked', 'Phone-number access blocked'), ('phone_masked', 'Masked phone number displayed'), ('bulk_report_action', 'Bulk report action'), ('deal_completed', 'Deal completed'), ('return_updated', 'Return updated'), ('conversation_reopened', 'Conversation reopened'), ('conversation_deactivated', 'Conversation deactivated')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('initiated', 'Conversation Started'), ('pending', 'Pending'), ('more_information', 'More Information Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('return_in_progress', 'Return in Progress'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=24),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='campus_location',
            field=models.CharField(blank=True, choices=[('main_entrance', 'Main Entrance'), ('library', 'Library'), ('cafeteria', 'Cafeteria'), ('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('student_affairs', 'Student Affairs'), ('sports_area', 'Sports Area'), ('administration', 'Administration Building'), ('conference_hall', 'Conference Hall'), ('university_garden', 'University Garden'), ('parking', 'Parking Area'), ('bus_stop', 'Shuttle or Bus Stop'), ('restroom', 'Restroom'), ('prayer_area', 'Prayer Area'), ('other', 'Other'), ('not_sure', 'Not Sure')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='image',
            field=models.ImageField(blank=True, upload_to=items.models.report_image_path, validators=[items.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('possible_match', 'Possible Match'), ('claim_in_progress', 'Claim in Progress'), ('return_arranged', 'Return Arranged'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('expired', 'Expired'), ('disputed', 'Disputed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('strong_match', 'Strong Possible Match'), ('new_claim', 'New Claim'), ('claim_updated', 'Claim Updated'), ('new_message', 'New Message'), ('return_updated', 'Return Updated'), ('saved_search_match', 'Saved Search Match'), ('expiration_warning', 'Report Expiration Warning'), ('deal_completed', 'Deal Completed'), ('conversation_reopened', 'Conversation Reopened'), ('conversation_deactivated', 'Conversation Deactivated'), ('contact_approved', 'Contact Request Approved'), ('contact_denied', 'Contact Request Denied'), ('report_status_changed', 'Report Status Changed'), ('admin_notice', 'Administrator Notice')], db_index=True, max_length=28),
        ),
        migrations.AddIndex(
            model_name='itemreport',
            index=models.Index(fields=['status', 'country', 'city', 'item_date'], name='items_itemr_status_3533d8_idx'),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_content_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custodyevent',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnarrangement',
            name='address_shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_delivery_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnarrangement',
            name='contact_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_arrangement', to='items.contactrequest'),
        ),
        migrations.AddField(
            model_name='custodyevent',
            name='arrangement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='items.returnarrangement'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedsearchnotification',
            name='item_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_search_notifications', to='items.itemreport'),
        ),
        migrations.AddField(
            model_name='savedsearchnotification',
            name='notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.notification'),
        ),
        migrations.AddField(
            model_name='savedsearchnotification',
            name='saved_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_reports', to='items.savedsearch'),
        ),
        migrations.AddField(
            model_name='trustedorganization',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnarrangement',
            name='trusted_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_arrangements', to='items.trustedorganization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='items.trustedorganization'),
        ),
        migrations.AddField(
            model_name='custodyevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.trustedorganization'),
        ),
        migrations.AddConstraint(
            model_name='contentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('reporter', 'target_type', 'target_identifier'), name='unique_open_content_report'),
        ),
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_saved_search_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='savedsearchnotification',
            constraint=models.UniqueConstraint(fields=('saved_search', 'item_report'), name='unique_saved_search_report_alert'),
        ),
        migrations.AddConstraint(
            model_name='trustedorganization',
            constraint=models.UniqueConstraint(fields=('name', 'country', 'city'), name='unique_trusted_organization_location'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_member'),
        ),
        migrations.RunPython(preserve_legacy_workflows, reverse_legacy_workflows),
    ]
