# Generated by Django 6.0.8 on 2026-08-14 10:15

import django.core.validators
import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_contentreport_custodyevent_organizationmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, storage=items.models.PrivateMediaStorage(), upload_to=items.models.message_attachment_path, validators=[items.models.validate_evidence_size, items.models.validate_evidence_content, django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'pdf'))]),
        ),
        migrations.AlterField(
            model_name='claimevidence',
            name='file',
            field=models.FileField(storage=items.models.PrivateMediaStorage(), upload_to=items.models.claim_evidence_path, validators=[items.models.validate_evidence_size, items.models.validate_evidence_content, django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'pdf'))]),
        ),
    ]
