# Generated by Django 6.0.8 on 2026-08-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_message_attachment_alter_claimevidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactauditlog',
            name='event_type',
            field=models.CharField(choices=[('request_created', 'Contact request created'), ('request_cancelled', 'Contact request cancelled'), ('request_approved', 'Request approved'), ('request_denied', 'Request denied'), ('request_more_info', 'More information requested'), ('additional_answer', 'Additional answer submitted'), ('claim_disputed', 'Claim disputed'), ('suspicious_claim', 'Suspicious claim reported'), ('permission_revoked', 'Permission revoked'), ('conversation_opened', 'Conversation opened'), ('message_sent', 'Message sent'), ('message_read', 'Message read'), ('phone_granted', 'Phone-number access granted'), ('phone_blocked', 'Phone-number access blocked'), ('phone_masked', 'Masked phone number displayed'), ('bulk_report_action', 'Bulk report action'), ('deal_completed', 'Deal completed'), ('return_updated', 'Return updated'), ('conversation_reopened', 'Conversation reopened'), ('conversation_deactivated', 'Conversation deactivated'), ('user_suspended', 'User suspended'), ('user_restored', 'User restored')], db_index=True, max_length=32),
        ),
    ]
