# Generated by Django 6.0.8 on 2026-08-18 11:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_contactauditlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreport',
            name='image_is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide this image from all public pages while preserving it for staff review.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university_eligibility_lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustodyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('intake_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('intake_point', models.CharField(max_length=120)),
                ('storage_reference', models.CharField(help_text='Private cabinet, shelf, room, or bin reference.', max_length=120)),
                ('status', models.CharField(choices=[('received', 'Received'), ('stored', 'Stored'), ('reserved', 'Reserved for approved claimant'), ('handed_over', 'Handed Over'), ('missing', 'Missing in Storage'), ('disposed', 'Disposition Recorded')], db_index=True, default='received', max_length=20)),
                ('is_high_value', models.BooleanField(default=False)),
                ('is_locked_storage', models.BooleanField(default=False)),
                ('requires_two_staff_release', models.BooleanField(default=False)),
                ('retention_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custody_record', to='items.itemreport')),
                ('handover_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_handovers', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-intake_at',),
                'permissions': (('manage_custody', 'Can manage University item custody'),),
            },
        ),
        migrations.CreateModel(
            name='CustodyMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('intake', 'Intake'), ('move', 'Storage movement'), ('review', 'Inventory review'), ('release', 'Release'), ('disposition', 'Disposition'), ('incident', 'Incident')], max_length=24)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('safe_note', models.CharField(blank=True, max_length=255)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('custody_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='items.custodyrecord')),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.CreateModel(
            name='StorageIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('custody_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='items.custodyrecord')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_incidents', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_storage_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
    ]
