# Generated by Django 6.0.8 on 2026-08-18 11:48

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_itemreport_image_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreport',
            name='private_sensitive_image',
            field=models.ImageField(blank=True, storage=items.models.PrivateMediaStorage(), upload_to=items.models.sensitive_report_image_path, validators=[items.models.validate_image_size]),
        ),
    ]
