# Generated by Django 6.0.8 on 2026-08-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_itemreport_private_sensitive_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnarrangement',
            name='return_method',
            field=models.CharField(blank=True, choices=[('security', 'University Lost and Found office'), ('trusted_organization', 'Authorized public authority')], max_length=32),
        ),
        migrations.AlterField(
            model_name='returnarrangement',
            name='status',
            field=models.CharField(choices=[('arranging', 'Arranging Return'), ('ready_pickup', 'Ready for Pickup'), ('handed_over', 'Handed Over'), ('awaiting_receipt', 'Awaiting Receipt Confirmation'), ('received', 'Received'), ('disputed', 'Disputed')], db_index=True, default='arranging', max_length=24),
        ),
    ]
