# Generated by Django 6.0.8 on 2026-08-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_alter_returnarrangement_return_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(db_index=True, max_length=120)),
                ('building', models.CharField(blank=True, db_index=True, max_length=120)),
                ('general_area', models.CharField(max_length=120)),
                ('location_type', models.CharField(choices=[('main_entrance', 'Main Entrance'), ('library', 'Library'), ('cafeteria', 'Cafeteria'), ('classroom', 'Classroom Building'), ('laboratory', 'Laboratory'), ('student_affairs', 'Student Affairs'), ('administration', 'Administration Building'), ('conference_hall', 'Conference Hall'), ('sports_area', 'Sports Area'), ('university_garden', 'University Garden'), ('parking', 'Parking Area'), ('bus_stop', 'Shuttle or Bus Stop'), ('restroom', 'Restroom'), ('prayer_area', 'Prayer Area'), ('other', 'Other'), ('not_sure', 'Not Sure')], default='not_sure', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('campus', 'building', 'general_area'),
                'constraints': [models.UniqueConstraint(fields=('campus', 'building', 'general_area'), name='unique_university_location')],
            },
        ),
        migrations.AddField(
            model_name='itemreport',
            name='university_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='items.universitylocation'),
        ),
    ]
