# Generated by Django 6.0.8 on 2026-08-18 13:50

import django.db.models.deletion
import items.models
from django.conf import settings
from django.db import migrations, models


def set_existing_scope_eligibility(apps, schema_editor):
    UserProfile = apps.get_model("items", "UserProfile")
    approved_domains = {
        value.strip().casefold().lstrip("@")
        for value in getattr(settings, "UNIVERSITY_EMAIL_DOMAINS", ())
        if value.strip()
    }
    for profile in UserProfile.objects.select_related("user").iterator():
        email = (profile.user.email or "").strip().casefold()
        domain = email.rsplit("@", 1)[1] if email.count("@") == 1 else ""
        eligible = bool(profile.email_verified_at and domain in approved_domains)
        profile.university_eligible = eligible
        profile.preferred_scope = "university" if eligible else "international"
        profile.save(update_fields=("university_eligible", "preferred_scope"))


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_universitylocation_itemreport_university_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custodyrecord',
            name='disposition_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custodyrecord',
            name='disposition_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_dispositions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custodyrecord',
            name='second_release_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_custody_release_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='scope',
            field=models.CharField(choices=[('university', 'University or Campus'), ('international', 'Outside University / International')], db_index=True, default='university', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_scope',
            field=models.CharField(choices=[('university', 'University or Campus'), ('international', 'Outside University / International')], default='international', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university_eligible',
            field=models.BooleanField(default=False, help_text='University eligibility is separate from ordinary email verification.'),
        ),
        migrations.RunPython(set_existing_scope_eligibility, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='returnarrangement',
            name='return_method',
            field=models.CharField(blank=True, choices=[('security', 'University Lost and Found office'), ('trusted_organization', 'Authorized public authority'), ('safe_public_meeting', 'In-person meeting in a safe public place'), ('local_authority', 'Trusted local authority or organization'), ('private_shipping', 'Privately arranged shipping (FindMatch does not provide shipping)')], max_length=32),
        ),
        migrations.CreateModel(
            name='ClaimAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('denied', 'Denied')], db_index=True, default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contact_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appeal', to='items.contactrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_claim_appeals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='DismissedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('found_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_as_found', to='items.itemreport')),
                ('lost_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_as_lost', to='items.itemreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'lost_report', 'found_report'), name='unique_dismissed_match')],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=items.models.additional_report_image_path, validators=[items.models.validate_image_size])),
                ('position', models.PositiveSmallIntegerField(default=2)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='items.itemreport')),
            ],
            options={
                'ordering': ('position', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('report', 'position'), name='unique_report_image_position'), models.CheckConstraint(condition=models.Q(('position__gte', 2), ('position__lte', 3)), name='report_image_position_2_to_3')],
            },
        ),
    ]
