# Generated by Django 6.0.8 on 2026-08-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_custodyrecord_disposition_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreport',
            name='item_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='date lost or found'),
        ),
    ]
