# Generated by Django 6.0.8 on 2026-08-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_alter_itemreport_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreport',
            name='custom_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='university_floor',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='university_room_or_area',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
